POST https://prod.theteller.net/v1.1/transaction/process HTTP/1.1
Content-Type: application/json
Authorization: Basic bmFtcGE1ZTM5OTUwMTJhOWZkOk1UQXlaV0V5WW1JeVltVTBZbVkxWlRJNE5Ea3lOakF3TVRSaU16WmhNek09

{
    "r-switch" : "MTN",
    "subscriber_number" : "233545466796",
    "transaction_id" : "000013410617",
    "amount" : "000000000020",
    "processing_code" : "000200",
    "merchant_id" : "TTM-00002569",
    "desc" : "nampa-market"
}