#!/usr/bin/env php

<?php

/**
 * Bootstraps the console application
 *
 * @author Prince Dorcis <princedorcis@gmail.com>
 */

require_once __DIR__ . '/vendor/autoload.php';

use Prinx\Rejoice\Console\ConsoleApp;

$console = new ConsoleApp;
$console->run();
